"""Manufacture subjects a pattern accepts, so every rule has an oracle.

Recog ships examples. Wappalyzer, Nuclei and WhatWeb ship none, and without an
example a translated pattern can only be checked by reading it - which is the
one method this project has already caught being wrong six times.

So the examples are made rather than found. A subject is generated by walking
the same parse tree the translator walks, and then - this is the part that
it trustworthy - it is put to **Python's own regex engine** against the
makes it evidence - runs each subject through the *original* PCRE. Only if
the real engine matches, and reports which text group N
captured, does the subject become an oracle. A bug in the generator therefore
produces a discarded sample, never a false confirmation: the generator proposes
and `re` disposes.

What this proves is agreement on the strings tested, not equivalence in
general. That is the honest claim, and it is worth having: against recog, where
genuine upstream examples exist to compare with, the generated samples agree
with them.
"""

import re

from pcre2lua import Parser, Untranslatable

# One representative character per Lua class shorthand. Chosen to be
# unambiguous - '7' is only ever a digit, 'q' only ever a letter - so a sample
# that matches cannot be matching for an unintended reason.
CLASS_SAMPLE = {
    "%d": "7", "%w": "q", "%a": "q", "%l": "q", "%u": "Q",
    "%s": " ", "%x": "7", "%p": ".", "%g": "q", "%c": "\t",
    "%D": "q", "%W": ".", "%A": ".", "%S": ".", "%P": "q",
}

# Tried in order when a negated class needs a character it does not contain.
# Ordered by how unambiguous each character is as a demonstration: a
# letter or a digit shows the class was exercised, where a dot or a
# space could be almost anything and reads as a broken sample.
CANDIDATES = "q7A1a3.-_/ ;:=<>"


def class_sample(body, negated):
    """One character the Lua class `[body]` accepts, or None."""
    members = set()
    index = 0
    while index < len(body):
        ch = body[index]
        if ch == "%" and index + 1 < len(body):
            nxt = body[index + 1]
            if nxt.isalpha():
                pick = CLASS_SAMPLE.get("%" + nxt)
                if pick:
                    members.add(pick)
            else:
                members.add(nxt)
            index += 2
            continue
        if index + 2 < len(body) and body[index + 1] == "-":
            # Expand the range rather than taking its low endpoint. Taking the
            # endpoint made [0-9.] offer "0", which loses to "." in CANDIDATES,
            # and every generated version came out as a bare dot - subjects
            # that verified a pattern while demonstrating nothing.
            upper = body[index + 2]
            if ord(upper) >= ord(ch) and ord(upper) - ord(ch) <= 32:
                members.update(chr(code) for code in range(ord(ch),
                                                               ord(upper) + 1))
            else:
                members.add(ch)
            index += 3
            continue
        members.add(ch)
        index += 1

    if not negated:
        for candidate in CANDIDATES:
            if candidate in members:
                return candidate
        return sorted(members)[0] if members else None

    for candidate in CANDIDATES:
        if candidate not in members:
            return candidate
    return None


def generate(node, choice, depth=0):
    """A string the node accepts, choosing branch `choice` at each
    alternation."""
    if depth > 40:
        raise Untranslatable("sample generation too deep")

    kind = node[0]

    if kind == 'lit':
        return node[1]
    if kind == 'any':
        return "q"
    if kind == 'class':
        pick = class_sample(node[1], node[2])
        if pick is None:
            raise Untranslatable("no character satisfies the class")
        return pick
    if kind in ('anchor', 'bound'):
        return ""

    if kind == 'rep':
        inner, lo, hi = node[1], node[2], node[3]
        # The smallest count that is both legal and non-empty where possible: a
        # sample that exercises zero repetitions proves nothing about the
        # repetition, and one that exercises many is slow and no more telling.
        wants_one = (hi is None or hi >= 1) and choice % 2 == 0
        count = lo if lo > 0 else (1 if wants_one else 0)
        return "".join(generate(inner, choice + step, depth + 1)
                       for step in range(count))

    if kind == 'group':
        alts = node[1]
        return "".join(generate(item, choice, depth + 1)
                       for item in alts[choice % len(alts)])

    raise Untranslatable("cannot sample %r" % (kind,))


def samples(pattern, want_group, ignore_case=False, dot_newline=False,
            count=6):
    """Subjects the original PCRE accepts, with what group `want_group`
    captures.

    @return list of (subject, captured) pairs; empty when nothing could be
            generated that the real engine agrees with
    """
    try:
        tree = Parser(strip_flags(pattern)).parse()
    except (Untranslatable, IndexError, ValueError):
        return []

    flags = 0
    if ignore_case:
        flags |= re.IGNORECASE
    if dot_newline:
        flags |= re.DOTALL
    try:
        compiled = re.compile(pattern, flags)
    except re.error:
        return []

    out = []
    seen = set()
    for choice in range(count):
        try:
            subject = generate(tree, choice)
        except (Untranslatable, IndexError, ValueError, RecursionError):
            continue
        if not subject or subject in seen:
            continue
        seen.add(subject)

        # The generator only proposes. This is where it is checked, by the
        # engine the pattern was written for.
        match = compiled.search(subject)
        if not match:
            continue
        if want_group is None:
            out.append((subject, None))
            continue
        try:
            captured = match.group(want_group)
        except (IndexError, re.error):
            continue
        if captured is None or captured == "":
            continue
        out.append((subject, captured))

    # A capture carrying a digit first. Every one of these subjects verifies
    # the pattern equally well, but the one recorded as the example is also
    # what a reader will judge the rule by - and "." or "q" reads as a broken
    # rule even when the rule is sound. The runtime rejects such a capture
    # anyway (version_of in vulners.nse), so demonstrating one is doubly
    # unhelpful.
    out.sort(key=lambda pair: (not any(c.isdigit() for c in (pair[1] or "")),
                               (pair[1] or "") != (pair[1] or "").strip()))
    return out


INLINE = re.compile(r"^\(\?[imsxu]+\)")


def strip_flags(pattern):
    match = INLINE.match(pattern)
    return pattern[match.end():] if match else pattern
